version: 0.1

target:
  disk: vda
  wipe: true

filesystem:
  layout: single
  type: ext4
  boot_mode: auto

rootfs:
  path: /config/rootfs/debian-rootfs.tar.gz

system:
  hostname: sp-qemu
  timezone: UTC
  locale: en_US.UTF-8

user:
  name: penguin
  sudo: true
  password_hash: "$6$dummyhash"

ssh:
  enable: true
  authorized_keys:
    - "ssh-ed25519 AAAAC3_EXAMPLE"

safety:
  require_erase_word: false
